CREATE TABLE IF NOT EXISTS `DB_NOTES_SYSTEM`.`TagNote_Details`(
    `TND_ID` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `TND_NoteID` BIGINT UNSIGNED NOT NULL,
    `TND_TagID` BIGINT UNSIGNED NOT NULL,
    KEY `IDX_FK_TND_Note` (`TND_NoteID`),
    KEY `IDX_FK_TND_User` (`TND_TagID`),
    CONSTRAINT `FK_TND_Note` FOREIGN KEY (`TND_NoteID`) REFERENCES `Notes` (`Note_ID`),
    CONSTRAINT `FK_TND_Tag` FOREIGN KEY (`TND_TagID`) REFERENCES `Tags` (`Tag_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;