CREATE TABLE IF NOT EXISTS `DB_NOTES_SYSTEM`.`Tags` (
    `Tag_Id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Tag_UUID` char(36) NOT NULL,
    `Tag_Name` VARCHAR(30) NOT NULL,
    `Tag_UserID` INT UNSIGNED NOT NULL,
    KEY `IDX_FK_Tag_User` (`Tag_UserID`),
    CONSTRAINT `UC_TagUUID` UNIQUE (`Tag_UUID`),
    CONSTRAINT `FK_Tag_User` FOREIGN KEY (`Tag_UserID`) REFERENCES `Users` (`User_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
-- 
USE `DB_NOTES_SYSTEM`;
-- 
CREATE INDEX `IDX_UUID` ON `Tags` (`Tag_UUID`);
-- 
CREATE INDEX `IDX_UserID` ON `Tags` (`Tag_UserID`);